#!/usr/bin/env node

const path = require('path');
const docDefinitionsLoader = require('./src/loading/document-definitions-loader');
const docDefinitionsValidator = require('./src/validation/document-definitions-validator');

const errorStatus = 1;

// Verify the correct number of commandline params
if (process.argv.length !== 3) {
  showUsage();

  process.exit(errorStatus);
}

const docDefinitionsFilename = process.argv[2];

const rawDocDefinitionsString = docDefinitionsLoader.load(docDefinitionsFilename);

const validationErrors = docDefinitionsValidator.validate(rawDocDefinitionsString, docDefinitionsFilename);

validationErrors.forEach((validationError) => {
  console.log(validationError);
});

const exitStatus = (validationErrors.length > 0) ? 1 : 0;
process.exit(exitStatus);

function showUsage() {
  const nodeBinary = path.basename(process.argv[0]);
  const scriptName = path.basename(process.argv[1]);

  console.log('A utility for validating the structure of a synctos document definitions file.\n');

  console.log('Usage:  ' + scriptName + ' <document_definitions_file>');
  console.log('   or:  ' + nodeBinary + ' ' + scriptName + ' <document_definitions_file>\n');

  console.log('Arguments:');
  console.log('    document_definitions_file');
  console.log('        Path to the JavaScript file that defines the document types for analysis\n');

  console.log('For example:  ' + scriptName + ' /path/to/my-sync-doc-definitions.js\n');

  console.log('See the README for more information.');
}
